# Generated by Django 6.0 on 2025-12-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Burning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('burning', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Infaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('young', models.IntegerField()),
                ('thought', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.IntegerField()),
                ('telegram_urls', models.CharField(max_length=100)),
                ('direction', models.ManyToManyField(to='course.burning')),
                ('select_branch', models.ManyToManyField(to='course.branch')),
            ],
        ),
    ]
